version: "3.1"
services:
  postgres:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamline
    ports:
      - "5432:5432"
